name: upload Azure function zip to Azure storage account

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  upload-azure-function-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create zip file with specific files
        run: |
          npm i -g azure-functions-core-tools@4 --unsafe-perm true
          # Add commands here to copy specific files into a new directory, for example:
          mkdir logzio_function
          cp host.json requirements.txt logzio_function/
          cp -r LogzioShipper logzio_function/
          # Now zip the directory
          cd logzio_function
          func pack --build-native-deps --python
          cp logzio_function.zip ../

      - name: Upload 'logzio_function' zip file to Azure storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload --overwrite true --account-name logzioblobtrigger --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} -f logzio_function.zip -c eventhub -n logzio_function.zip
